version: 0.0
os: linux
files:
  - source: /home/ubuntu/build
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
